language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t mariasurgan/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mariasurgan/docker-react npm run test
