language: generic 
sudo: required
services:
  - docker 

before_install:
  - docker build -t mariasurgan/docker-react -f Dockerfil.dev .

script:
  - docker run mariasurgan/docker-react npm run test -- --coverage
